package com.powers.spell;

/** Server-side behaviours understood by the grimoire casting engine. */
public enum SpellEffect {
	SOUL_COMPASS,
	TRACKING_MARK,
	WEATHER_SIGIL,
	DIMENSIONAL_ANCHOR,
	BINDING_SIGIL,
	ANTI_PORTAL_FIELD,
	KINETIC_WARD,
	VITALITY_TRANSFER,
	HEX,
	CONCEALMENT_VEIL,
	PURIFICATION_CIRCLE,
	ROOT_BINDING,
	SANCTUARY_GROWTH,
	INFERNAL_SEAL,
	BANISHMENT_CIRCLE,
	CONTROLLED_HELLFIRE,
	WARD_BREAKING_RITUAL,
	COUNTERSPELL,
	DISPEL,
	RITUAL_AMPLIFICATION
}
